apiVersion: 1

datasources:
  - name: NeonDB
    type: postgres
    access: proxy
    url: ${DBT_NEON_HOST}:5432
    user: ${DBT_NEON_USER}
    database: ${DBT_NEON_DB}
    secureJsonData:
      password: ${NEON_DB_PASSWORD}
    jsonData:
      sslmode: require
      postgresVersion: 16
    isDefault: false
    editable: false
